server:
  servlet:
    #Personalisierte URL Pfad damit die Anwendung unter unterschiedliche URL angesprochen werden kann
    context-path: /frontend-carabasa
management:
  # Prometheus Konfiguration damit die Anwendung Metriken genieriert und die über Webserver zur Verfügung stellt
  endpoints:
    web:
      exposure:
        include: "info, health, prometheus"
  metrics:
    tags:
      application: frontend-carabasa
service:
  routingKey: "carabasa-kubecoin"
  # Spring WebClient Endpoints
  backends:
    worker: "http://worker-carabasa/worker-carabasa"
spring:
  #RabbitMQ Konfiguration
  rabbitmq:
    port: 5672
    username: cnc
    password: cnc
    virtual-host: /cnc
    ssl:
      enabled: false

