{
 "title": "kubecoins-carabasa",
 "description": "Abschluss Projekt KubeCoins",
 "time": { "from": "2021-01-12T05:33:26.786Z", "to": "2021-01-12T09:33:26.786Z" },
 "panels": [
  {
   "title": "Randomizer Requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(randomizer_requests_total{application=\"randomizer-carabasa\"}[5m])"
    }
   ]
  },
  {
   "title": "Worker Requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(worker_requests_total{application=\"worker-carabasa\"}[10m])"
    }
   ]
  },
  {
   "title": "Hasher Requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "hasher_requests_total{application=\"hasher-carabasa\"}"
    }
   ]
  },
  {
   "title": "Frontend Requests",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "frontend_requests_total{application=\"frontend-carabasa\"}"
    },
    {}
   ]
  }
 ]
}