apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-{{.Values.author }}
  labels:
    app: frontend
    author: {{.Values.author }}
spec:
  replicas: {{.Values.replicaCount }}
  selector:
    matchLabels:
      app: frontend
      author: {{ .Values.author }}
  template:
    metadata:
      labels:
        app: frontend
        author: {{.Values.author }}
    spec:
      containers:
        - name: frontend-{{.Values.author }}
          image: {{ .Values.image }}
          env:
            - name: SPRING_RABBITMQ_HOST
              value: amq-rabbitmq-ha.devtools
          resources:
            limits:
              memory: 256Mi
            requests:
              memory: 32Mi
          livenessProbe:
            initialDelaySeconds: 15
            httpGet:
              path: /frontend-carabasa/actuator/health/liveness
              port: 8080
          readinessProbe:
            initialDelaySeconds: 15
            httpGet:
              path: /frontend-carabasa/actuator/health/readiness
              port: 8080