# Ingress erlaubt die erstellte Pods auch von extern zugreifen, ohne Ingress sind Pods nur Cluster-intern ansprechbar
# Ingress-Ressourcen verbinden einen Host und Path zu einem Service
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend-carabasa
  labels:
    app: frontend
    author: carabasa
spec:
  rules:
    - host: kube.informatik.hs-furtwangen.de
      http:
        paths:
          - pathType: Prefix
            path: "/frontend-carabasa"
            backend:
              service:
                name: frontend-carabasa
                port:
                  number: 80
